CREATE TABLE `competition_portfolios` (`id` text PRIMARY KEY NOT NULL,`owner_email` text NOT NULL,`athlete_id` text,`display_name` text NOT NULL,`competition_name` text NOT NULL,`birth_year` integer,`academy_name` text,`current_rank` text,`visibility` text DEFAULT 'private' NOT NULL,`verification_status` text DEFAULT 'self_reported' NOT NULL,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);
CREATE TABLE `competition_results` (`id` text PRIMARY KEY NOT NULL,`portfolio_id` text NOT NULL,`event_name` text NOT NULL,`event_date` integer NOT NULL,`organizer` text NOT NULL,`location_text` text,`discipline` text NOT NULL,`age_division` text,`belt_division` text,`weight_division` text,`placement` integer,`wins` integer DEFAULT 0 NOT NULL,`losses` integer DEFAULT 0 NOT NULL,`draws` integer DEFAULT 0 NOT NULL,`submission_wins` integer DEFAULT 0 NOT NULL,`source_url` text,`source_record_id` text,`verification_status` text DEFAULT 'self_reported' NOT NULL,`verified_by` text,`verified_at` integer,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);
CREATE TABLE `external_competition_profiles` (`id` text PRIMARY KEY NOT NULL,`portfolio_id` text NOT NULL,`provider` text NOT NULL,`profile_url` text NOT NULL,`external_athlete_id` text,`claimed_name` text,`match_status` text DEFAULT 'unverified' NOT NULL,`match_confidence` integer,`last_checked_at` integer,`created_at` integer NOT NULL,`updated_at` integer NOT NULL);
CREATE TABLE `competition_evidence` (`id` text PRIMARY KEY NOT NULL,`portfolio_id` text NOT NULL,`result_id` text,`object_key` text NOT NULL,`file_name` text NOT NULL,`content_type` text NOT NULL,`byte_size` integer NOT NULL,`sha256` text NOT NULL,`evidence_type` text NOT NULL,`source_provider` text,`status` text DEFAULT 'submitted' NOT NULL,`uploaded_by` text NOT NULL,`created_at` integer NOT NULL);
CREATE TABLE `record_verification_events` (`id` text PRIMARY KEY NOT NULL,`portfolio_id` text NOT NULL,`result_id` text,`external_profile_id` text,`event_type` text NOT NULL,`outcome` text NOT NULL,`confidence` integer,`reason` text,`actor_email` text NOT NULL,`created_at` integer NOT NULL);
CREATE UNIQUE INDEX `portfolio_owner_unique` ON `competition_portfolios` (`owner_email`);
CREATE UNIQUE INDEX `external_profile_unique` ON `external_competition_profiles` (`portfolio_id`,`provider`,`profile_url`);
CREATE INDEX `competition_result_portfolio_date_idx` ON `competition_results` (`portfolio_id`,`event_date`);
CREATE INDEX `competition_evidence_result_idx` ON `competition_evidence` (`result_id`,`status`);
