"use client";

import { useMemo, useState } from "react";

type NavKey = "command" | "athletes" | "prep" | "review" | "library";
const nav: { key: NavKey; label: string; icon: string }[] = [
  { key: "command", label: "Command", icon: "⌂" }, { key: "athletes", label: "Athletes", icon: "◉" },
  { key: "prep", label: "Competition", icon: "◇" }, { key: "review", label: "Match Review", icon: "▶" },
  { key: "library", label: "Knowledge", icon: "▤" },
];
const readiness = [{ label: "Technical execution", value: 82, delta: "+6" }, { label: "Positional control", value: 76, delta: "+9" }, { label: "Competition composure", value: 88, delta: "+3" }];
const athletes = [
  { initials: "AM", name: "Avery M.", meta: "Grey · 11 · 88 lb", ready: 86, trend: "+7", focus: "Guard retention" },
  { initials: "JL", name: "Jordan L.", meta: "Yellow · 12 · 103 lb", ready: 79, trend: "+4", focus: "Passing chains" },
  { initials: "RK", name: "Riley K.", meta: "Grey/White · 9 · 72 lb", ready: 73, trend: "+11", focus: "Top control" },
  { initials: "TS", name: "Taylor S.", meta: "Grey · 10 · 80 lb", ready: 68, trend: "−2", focus: "Reset discipline" },
];
const events = [
  { date: "AUG 29", name: "Regional Youth Open", detail: "7 athletes · Gi / No-Gi", phase: "Final prep", tone: "maroon" },
  { date: "SEP 12", name: "Academy Development Day", detail: "18 athletes · Internal", phase: "Build", tone: "gray" },
  { date: "OCT 03", name: "State Championship", detail: "12 projected · Gi / No-Gi", phase: "Base", tone: "gold" },
];
function Ring({ value }: { value: number }) { return <div className="ring" style={{ "--score": `${value * 3.6}deg` } as React.CSSProperties}><span>{value}</span><small>READY</small></div>; }

const modules = {
  athletes: { eyebrow: "LONGITUDINAL DEVELOPMENT", title: "Athlete Development Registry", summary: "One governed record from first class through long-term development.", metric: "14", metricLabel: "ACTIVE ATHLETES", actions: ["Add observation", "Create assessment", "Invite parent"], lanes: [{ name: "Technical foundation", value: 81, note: "12 progressing" }, { name: "Decision quality", value: 74, note: "3 interventions" }, { name: "Training behavior", value: 89, note: "Stable" }] },
  prep: { eyebrow: "COMPETITION OPERATIONS", title: "Competition Readiness Board", summary: "Convert coach intent into safe, time-bound preparation and clear corner priorities.", metric: "4", metricLabel: "DAYS TO ROSTER LOCK", actions: ["Add tournament", "Build game plan", "Lock roster"], lanes: [{ name: "Registration verified", value: 100, note: "7 of 7" }, { name: "Rules prepared", value: 86, note: "1 review due" }, { name: "Game-plan rehearsed", value: 71, note: "2 below target" }] },
  review: { eyebrow: "EVIDENCE TO ACTION", title: "Match Review Workbench", summary: "Turn competition footage and coach observations into the next training decision.", metric: "3", metricLabel: "REVIEWS PENDING", actions: ["Upload match", "Tag sequence", "Assign review"], lanes: [{ name: "First-control success", value: 68, note: "−4 vs target" }, { name: "Escape efficiency", value: 77, note: "+9 this cycle" }, { name: "Scoring conversion", value: 83, note: "On target" }] },
  library: { eyebrow: "INSTITUTIONAL LEARNING", title: "Academy Knowledge Repository", summary: "Retain approved drills, playbooks, rules, lessons, and coaching standards as academy IP.", metric: "126", metricLabel: "GOVERNED ASSETS", actions: ["Add resource", "Create playbook", "Start review"], lanes: [{ name: "Technique library", value: 92, note: "68 assets" }, { name: "Competition playbooks", value: 78, note: "31 assets" }, { name: "Coach standards", value: 84, note: "27 assets" }] },
} as const;

function ModulePanel({ type, onAction }: { type: Exclude<NavKey, "command">; onAction: (value: string) => void }) {
  const module = modules[type];
  return <section className="module-panel"><div className="module-lead"><div><p>{module.eyebrow}</p><h2>{module.title}</h2><span>{module.summary}</span></div><div className="module-metric"><strong>{module.metric}</strong><small>{module.metricLabel}</small></div></div><div className="module-body"><div className="module-actions">{module.actions.map((action, index) => <button className={index === 0 ? "featured" : ""} key={action} onClick={() => onAction(`${action} workflow opened.`)}><i>{index === 0 ? "+" : "→"}</i><span>{action}<small>{index === 0 ? "Primary action" : "Governed workflow"}</small></span></button>)}</div><div className="module-lanes">{module.lanes.map((lane) => <div key={lane.name}><span><b>{lane.name}</b><em>{lane.note}</em></span><div><i style={{ width: `${lane.value}%` }}/></div><strong>{lane.value}%</strong></div>)}</div><aside><p>DECISION SUPPORT</p><strong>{type === "prep" ? "Two athletes require final game-plan rehearsal before roster lock." : type === "review" ? "Guard recovery remains the highest-leverage review theme." : type === "library" ? "Seven resources require annual coach validation." : "Three athletes require focused coach intervention this week."}</strong><button onClick={() => onAction("Decision brief added to the coach review queue.")}>Queue decision brief →</button></aside></div></section>;
}

function WorkflowModal({ action, close, complete }: { action: string; close: () => void; complete: (message: string) => void }) {
  const upload = action === "Upload match"; const consent = action === "Invite parent"; const event = action === "Add tournament"; const athlete = action === "Add observation" || action === "Create assessment";
  return <div className="modal" role="dialog" aria-modal="true"><form onSubmit={(e)=>{e.preventDefault();complete(`${action} saved to the governed workspace.`)}}><button type="button" className="close" onClick={close}>×</button><p>GOVERNED WORKFLOW</p><h2>{action}</h2><label>Athlete<select name="athleteId"><option value="athlete-demo-1">Avery M.</option><option value="athlete-demo-2">Jordan L.</option><option value="athlete-demo-3">Riley K.</option></select></label>{event&&<><label>Tournament name<input required placeholder="Regional Youth Open"/></label><label>Event date<input required type="date"/></label><label>Ruleset<select><option>JJWL</option><option>IBJJF</option><option>NAGA</option><option>Academy-defined</option></select></label></>}{upload&&<><label>Match video<input required type="file" accept="video/*"/></label><label>Review tags<input placeholder="guard recovery, first control, scoring"/></label><div className="safety"><b>Consent verified</b><span>Upload is restricted to performance review and academy-authorized viewers.</span></div></>}{consent&&<><label>Parent or guardian email<input required type="email" placeholder="guardian@example.com"/></label><label>Consent scope<select><option>Performance records</option><option>Internal match video</option><option>Tournament operations</option></select></label></>}{athlete&&<><label>Development domain<select><option>Technical execution</option><option>Positional control</option><option>Decision quality</option><option>Training behavior</option></select></label><label>Coach evidence<textarea placeholder="Record observable behavior—not assumptions or diagnoses."/></label></>}{!event&&!upload&&!consent&&!athlete&&<label>Workflow note<textarea placeholder="Add the governing intent, evidence, and expected outcome."/></label>}<div className="safety"><b>Release control</b><span>Records are role-restricted, auditable, and subject to parent consent and retention policy.</span></div><button className="primary" type="submit">Save governed record</button></form></div>;
}

export default function CommandCenter() {
  const [active, setActive] = useState<NavKey>("command"); const [showPlan, setShowPlan] = useState(false);
  const [brief, setBrief] = useState(""); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState(""); const [workflow,setWorkflow]=useState(""); const [role,setRole]=useState("Administrator");
  const title = useMemo(() => nav.find((item) => item.key === active)?.label ?? "Command", [active]);
  async function generateBrief() { setLoading(true); setNotice(""); try { const response = await fetch("/api/coach", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ athlete: "Avery M.", focus: "Guard retention", days: 7 }) }); const data = await response.json(); setBrief(data.brief || "Plan generated and queued for coach review."); } catch { setBrief("AI service is temporarily unavailable. The baseline plan remains active."); } finally { setLoading(false); } }
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">M</div><div><strong>MATIQ</strong><span>YOUTH JIU-JITSU</span></div></div>
      <nav aria-label="Primary navigation"><p className="nav-label">OPERATIONS</p>{nav.map((item) => <button key={item.key} className={active === item.key ? "active" : ""} onClick={() => setActive(item.key)}><i>{item.icon}</i>{item.label}{item.key === "review" && <b>3</b>}</button>)}<p className="nav-label nav-gap">SYSTEM</p><button onClick={() => setNotice("Analytics workspace queued for the academy pilot.")}><i>⌁</i>Analytics</button><button onClick={() => setNotice("Academy controls are restricted to authorized administrators.")}><i>⚙</i>Academy settings</button></nav>
      <div className="academy-card"><span>APEX YOUTH ACADEMY</span><strong>Pilot workspace</strong><small>14 athletes · 4 coaches</small><div><em>Owner-only</em><b>PRO</b></div></div>
      <div className="role-control"><label>ACTIVE ROLE</label><select value={role} onChange={(e)=>setRole(e.target.value)}><option>Administrator</option><option>Coach</option><option>Parent</option><option>Read-only reviewer</option></select></div><div className="user"><div>BB</div><span><strong>Benjamin</strong><small>{role}</small></span><button aria-label="Account options">•••</button></div>
    </aside>
    <section className="workspace"><div className="executive-frame" aria-hidden="true"><i/><i/><i/><i/></div><header><div><p>ACADEMY OPERATIONS / <span>{title.toUpperCase()}</span></p><h1>{active === "command" ? "Performance Command Center" : title}</h1></div><div className="header-actions"><button className="icon-button" aria-label="Notifications">♢<b>2</b></button><button className="primary" onClick={() => setShowPlan(true)}>＋ New plan</button></div></header>
      <div className="command-rail"><span><i className="rail-seal">M</i><b>DECISION SUPERIORITY SYSTEM</b></span><span>DATA STATE <b>GOVERNED</b></span><span>AI CONTROL <b>COACH-VERIFIED</b></span><span>ACCESS <b>{role.toUpperCase()}</b></span><em>DTG 22 AUG 2026</em></div>
      {notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice("")}>×</button></div>}
      {active !== "command" && <ModulePanel type={active} onAction={setWorkflow}/>} 
      <section className="status-strip"><div><span className="live-dot"/>PROGRAM STATUS</div><strong>Competition cycle · Week 3 of 6</strong><p>Next decision gate: roster lock in 4 days</p><button onClick={() => setActive("prep")}>Open cycle →</button></section>
      <div className="top-grid"><article className="card overview"><div className="card-heading"><div><p>ACADEMY READINESS</p><h2>Competition cohort</h2></div><button>Last 30 days⌄</button></div><div className="readiness"><Ring value={81}/><div className="metrics">{readiness.map((r) => <div key={r.label}><span>{r.label}<b>↑ {r.delta}%</b></span><div><i style={{width: `${r.value}%`}}/></div><strong>{r.value}</strong></div>)}</div></div><footer><span><i className="good"/>10 on track</span><span><i className="warn"/>3 require attention</span><button onClick={() => setActive("athletes")}>View roster →</button></footer></article>
        <article className="card ai-card"><div className="ai-label"><span>✦</span> MATIQ INTELLIGENCE <b>AI</b></div><h2>Coach decision brief</h2><p className="insight">Guard retention is the highest-leverage training priority across the competition cohort.</p><div className="evidence"><span>EVIDENCE</span><p>7 of 14 athletes lost first control during opponent pressure. Recovery rate improved 18% after constraint rounds.</p></div>{brief && <div className="generated">{brief}</div>}<button className="ai-action" onClick={generateBrief} disabled={loading}>{loading ? "Building brief…" : "Generate 7-day intervention"}<span>→</span></button><small>Coach approval required before athlete delivery.</small></article></div>
      <div className="lower-grid"><article className="card roster"><div className="card-heading"><div><p>ATHLETE INTELLIGENCE</p><h2>Roster readiness</h2></div><button onClick={() => setActive("athletes")}>All athletes →</button></div><div className="table-head"><span>ATHLETE</span><span>READINESS</span><span>30D</span><span>PRIORITY</span></div>{athletes.map((a) => <button className="athlete-row" key={a.name} onClick={() => setNotice(`${a.name}: development profile opened.`)}><span className="athlete"><i>{a.initials}</i><b>{a.name}<small>{a.meta}</small></b></span><span className="mini-score"><b>{a.ready}</b><i><em style={{width: `${a.ready}%`}}/></i></span><span className={a.trend.includes("−") ? "down" : "up"}>{a.trend}</span><span className="tag">{a.focus}</span></button>)}</article>
        <article className="card calendar"><div className="card-heading"><div><p>FORCE CALENDAR</p><h2>Upcoming events</h2></div><button onClick={() => setActive("prep")}>Calendar →</button></div>{events.map((e) => <div className="event" key={e.name}><div className={`date ${e.tone}`}>{e.date.split(" ")[0]}<strong>{e.date.split(" ")[1]}</strong></div><div><strong>{e.name}</strong><span>{e.detail}</span></div><em className={e.tone}>{e.phase}</em></div>)}<div className="weight-watch"><span>⚖</span><div><strong>Weight governance</strong><p>All athletes inside declared safety bands. No acute cuts authorized.</p></div><b>COMPLIANT</b></div></article></div>
      <footer className="system-footer"><span><i/>Systems nominal</span><p>Privacy-first · Parent-controlled · Coach-verified AI</p><b>MATIQ v0.1 PILOT</b></footer>
    </section>
    {showPlan && <div className="modal" role="dialog" aria-modal="true" aria-label="Create development plan"><form onSubmit={(e) => { e.preventDefault(); setShowPlan(false); setNotice("Draft plan created. Coach review is the next control point."); }}><button type="button" className="close" onClick={() => setShowPlan(false)}>×</button><p>NEW DEVELOPMENT PLAN</p><h2>Build a governed training cycle</h2><label>Athlete<select><option>Avery M.</option><option>Jordan L.</option><option>Riley K.</option></select></label><label>Primary outcome<select><option>Competition readiness</option><option>Technical development</option><option>Return to training</option></select></label><label>Coach intent<textarea defaultValue="Improve first control, guard retention, and decision speed without increasing training load."/></label><div className="safety"><b>Safety control</b><span>Plans remain drafts until approved by an authorized coach. No autonomous medical or weight-cut guidance.</span></div><button className="primary" type="submit">Create draft plan</button></form></div>}
    {workflow && <WorkflowModal action={workflow} close={()=>setWorkflow("")} complete={(message)=>{setWorkflow("");setNotice(message)}}/>}
  </main>;
}
