import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const academies = sqliteTable("academies", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  plan: text("plan").notNull().default("pilot"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const athletes = sqliteTable("athletes", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  alias: text("alias").notNull(),
  birthYear: integer("birth_year").notNull(),
  belt: text("belt").notNull(),
  consentStatus: text("consent_status").notNull().default("pending"),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const observations = sqliteTable("observations", {
  id: text("id").primaryKey(),
  athleteId: text("athlete_id").notNull(),
  authorEmail: text("author_email").notNull(),
  category: text("category").notNull(),
  rating: integer("rating").notNull(),
  note: text("note"),
  observedAt: integer("observed_at", { mode: "timestamp" }).notNull(),
});
export const competitionPlans = sqliteTable("competition_plans", {
  id: text("id").primaryKey(),
  athleteId: text("athlete_id").notNull(),
  eventName: text("event_name").notNull(),
  status: text("status").notNull().default("draft"),
  coachIntent: text("coach_intent").notNull(),
  approvedBy: text("approved_by"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const mediaObjects = sqliteTable("media_objects", {
  id: text("id").primaryKey(),
  academyId: text("academy_id"),
  athleteId: text("athlete_id").notNull(),
  objectKey: text("object_key").notNull(),
  kind: text("kind").notNull(),
  consentScope: text("consent_scope").notNull(),
  retentionUntil: integer("retention_until", { mode: "timestamp" }),
  retentionPolicyId: text("retention_policy_id"),
  storageClass: text("storage_class").notNull().default("standard"),
  lifecycleState: text("lifecycle_state").notNull().default("active"),
  legalHold: integer("legal_hold", { mode: "boolean" }).notNull().default(false),
  byteSize: integer("byte_size").notNull().default(0),
  parentMediaId: text("parent_media_id"),
  lastAccessedAt: integer("last_accessed_at", { mode: "timestamp" }),
  deletedAt: integer("deleted_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const aiAudit = sqliteTable("ai_audit", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  actorEmail: text("actor_email").notNull(),
  useCase: text("use_case").notNull(),
  inputClass: text("input_class").notNull(),
  outputStatus: text("output_status").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const memberships = sqliteTable("memberships", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  email: text("email").notNull(),
  role: text("role").notNull(),
  status: text("status").notNull().default("active"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const tournaments = sqliteTable("tournaments", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  name: text("name").notNull(),
  eventDate: integer("event_date", { mode: "timestamp" }).notNull(),
  ruleset: text("ruleset").notNull(),
  registrationDeadline: integer("registration_deadline", { mode: "timestamp" }),
  status: text("status").notNull().default("planned"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const consents = sqliteTable("consents", {
  id: text("id").primaryKey(),
  academyId: text("academy_id"),
  athleteId: text("athlete_id").notNull(),
  parentEmail: text("parent_email").notNull(),
  scope: text("scope").notNull(),
  status: text("status").notNull().default("pending"),
  expiresAt: integer("expires_at", { mode: "timestamp" }),
  recordedBy: text("recorded_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const rightsRequests = sqliteTable("rights_requests", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  requesterEmail: text("requester_email").notNull(),
  athleteId: text("athlete_id"),
  requestType: text("request_type").notNull(),
  status: text("status").notNull().default("received"),
  dueAt: integer("due_at", { mode: "timestamp" }),
  completedAt: integer("completed_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const auditEvents = sqliteTable("audit_events", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  actorEmail: text("actor_email").notNull(),
  action: text("action").notNull(),
  objectType: text("object_type").notNull(),
  objectId: text("object_id"),
  outcome: text("outcome").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const trainingSessions = sqliteTable("training_sessions", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  athleteId: text("athlete_id").notNull(),
  sessionType: text("session_type").notNull(),
  sessionDate: integer("session_date", { mode: "timestamp" }).notNull(),
  durationMinutes: integer("duration_minutes").notNull(),
  intensity: integer("intensity").notNull(),
  focus: text("focus").notNull(),
  notes: text("notes"),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const skillProgress = sqliteTable("skill_progress", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  athleteId: text("athlete_id").notNull(),
  domain: text("domain").notNull(),
  skillName: text("skill_name").notNull(),
  level: integer("level").notNull(),
  evidence: text("evidence"),
  assessedBy: text("assessed_by").notNull(),
  assessedAt: integer("assessed_at", { mode: "timestamp" }).notNull(),
});
export const promotionProgress = sqliteTable("promotion_progress", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  athleteId: text("athlete_id").notNull(),
  currentRank: text("current_rank").notNull(),
  targetRank: text("target_rank").notNull(),
  technicalScore: integer("technical_score").notNull(),
  attendanceScore: integer("attendance_score").notNull(),
  competitionScore: integer("competition_score").notNull(),
  characterScore: integer("character_score").notNull(),
  coachStatus: text("coach_status").notNull().default("developing"),
  coachNote: text("coach_note"),
  reviewedBy: text("reviewed_by"),
  reviewedAt: integer("reviewed_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const videoEvaluations = sqliteTable("video_evaluations", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  mediaId: text("media_id").notNull(),
  athleteId: text("athlete_id").notNull(),
  eventName: text("event_name").notNull(),
  division: text("division"),
  result: text("result"),
  status: text("status").notNull().default("queued"),
  analysisJson: text("analysis_json"),
  coachVerifiedBy: text("coach_verified_by"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const videoMarkers = sqliteTable("video_markers", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  evaluationId: text("evaluation_id").notNull(),
  athleteId: text("athlete_id").notNull(),
  second: integer("second").notNull(),
  category: text("category").notNull(),
  outcome: text("outcome").notNull(),
  note: text("note"),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const curriculumItems = sqliteTable("curriculum_items", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  name: text("name").notNull(),
  domain: text("domain").notNull(),
  rankBand: text("rank_band").notNull(),
  requiredLevel: integer("required_level").notNull(),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const attendance = sqliteTable("attendance", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  athleteId: text("athlete_id").notNull(),
  sessionDate: integer("session_date", { mode: "timestamp" }).notNull(),
  classType: text("class_type").notNull(),
  status: text("status").notNull(),
  recordedBy: text("recorded_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const storagePolicies = sqliteTable("storage_policies", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  name: text("name").notNull(),
  activeDays: integer("active_days").notNull().default(90),
  retainedDays: integer("retained_days").notNull().default(365),
  deleteAfterDays: integer("delete_after_days").notNull().default(365),
  temporaryDays: integer("temporary_days").notNull().default(7),
  draftEvaluationDays: integer("draft_evaluation_days").notNull().default(90),
  verifiedEvaluationDays: integer("verified_evaluation_days").notNull().default(1095),
  status: text("status").notNull().default("active"),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const mediaDerivatives = sqliteTable("media_derivatives", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  sourceMediaId: text("source_media_id").notNull(),
  objectKey: text("object_key").notNull(),
  kind: text("kind").notNull(),
  retentionPolicyId: text("retention_policy_id"),
  retentionUntil: integer("retention_until", { mode: "timestamp" }),
  legalHold: integer("legal_hold", { mode: "boolean" }).notNull().default(false),
  byteSize: integer("byte_size").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const legalHolds = sqliteTable("legal_holds", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  mediaId: text("media_id").notNull(),
  reason: text("reason").notNull(),
  status: text("status").notNull().default("active"),
  authorizedBy: text("authorized_by").notNull(),
  placedAt: integer("placed_at", { mode: "timestamp" }).notNull(),
  releasedBy: text("released_by"),
  releasedAt: integer("released_at", { mode: "timestamp" }),
});
export const deletionReceipts = sqliteTable("deletion_receipts", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  mediaId: text("media_id").notNull(),
  objectKeyHash: text("object_key_hash").notNull(),
  policyId: text("policy_id"),
  reason: text("reason").notNull(),
  deletedBy: text("deleted_by").notNull(),
  outcome: text("outcome").notNull(),
  deletedAt: integer("deleted_at", { mode: "timestamp" }).notNull(),
});
export const storageUsageDaily = sqliteTable("storage_usage_daily", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  usageDate: text("usage_date").notNull(),
  objectCount: integer("object_count").notNull(),
  totalBytes: integer("total_bytes").notNull(),
  standardBytes: integer("standard_bytes").notNull(),
  infrequentBytes: integer("infrequent_bytes").notNull(),
  capturedAt: integer("captured_at", { mode: "timestamp" }).notNull(),
});
export const subscriptions = sqliteTable("subscriptions", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  planCode: text("plan_code").notNull(),
  status: text("status").notNull().default("trialing"),
  billingProvider: text("billing_provider").notNull().default("manual"),
  providerCustomerId: text("provider_customer_id"),
  providerSubscriptionId: text("provider_subscription_id"),
  athleteLimit: integer("athlete_limit").notNull().default(10),
  storageLimitBytes: integer("storage_limit_bytes").notNull().default(10737418240),
  currentPeriodEnd: integer("current_period_end", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const invoices = sqliteTable("invoices", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  subscriptionId: text("subscription_id").notNull(),
  amountCents: integer("amount_cents").notNull(),
  currency: text("currency").notNull().default("usd"),
  status: text("status").notNull(),
  providerInvoiceId: text("provider_invoice_id"),
  dueAt: integer("due_at", { mode: "timestamp" }),
  paidAt: integer("paid_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const usageMeters = sqliteTable("usage_meters", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  metric: text("metric").notNull(),
  quantity: integer("quantity").notNull(),
  periodKey: text("period_key").notNull(),
  recordedAt: integer("recorded_at", { mode: "timestamp" }).notNull(),
});
export const analysisJobs = sqliteTable("analysis_jobs", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  evaluationId: text("evaluation_id").notNull(),
  jobType: text("job_type").notNull(),
  status: text("status").notNull().default("queued"),
  attempts: integer("attempts").notNull().default(0),
  priority: integer("priority").notNull().default(50),
  leaseUntil: integer("lease_until", { mode: "timestamp" }),
  errorCode: text("error_code"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  completedAt: integer("completed_at", { mode: "timestamp" }),
});
export const athleteGoals = sqliteTable("athlete_goals", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  athleteId: text("athlete_id").notNull(),
  title: text("title").notNull(),
  category: text("category").notNull(),
  targetValue: integer("target_value"),
  currentValue: integer("current_value").notNull().default(0),
  targetDate: integer("target_date", { mode: "timestamp" }),
  status: text("status").notNull().default("active"),
  coachNote: text("coach_note"),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const trainingBlocks = sqliteTable("training_blocks", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  athleteId: text("athlete_id").notNull(),
  name: text("name").notNull(),
  objective: text("objective").notNull(),
  startDate: integer("start_date", { mode: "timestamp" }).notNull(),
  endDate: integer("end_date", { mode: "timestamp" }).notNull(),
  weeklySessions: integer("weekly_sessions").notNull(),
  status: text("status").notNull().default("planned"),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const notifications = sqliteTable("notifications", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  recipientEmail: text("recipient_email").notNull(),
  category: text("category").notNull(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  actionUrl: text("action_url"),
  status: text("status").notNull().default("queued"),
  dedupeKey: text("dedupe_key"),
  scheduledAt: integer("scheduled_at", { mode: "timestamp" }).notNull(),
  sentAt: integer("sent_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const productEvents = sqliteTable("product_events", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  actorEmail: text("actor_email"),
  eventName: text("event_name").notNull(),
  objectType: text("object_type"),
  objectId: text("object_id"),
  propertiesJson: text("properties_json"),
  occurredAt: integer("occurred_at", { mode: "timestamp" }).notNull(),
});
export const serviceIncidents = sqliteTable("service_incidents", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  severity: text("severity").notNull(),
  title: text("title").notNull(),
  status: text("status").notNull().default("open"),
  impact: text("impact").notNull(),
  ownerEmail: text("owner_email"),
  openedAt: integer("opened_at", { mode: "timestamp" }).notNull(),
  resolvedAt: integer("resolved_at", { mode: "timestamp" }),
});
export const academySettings = sqliteTable("academy_settings", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  legalName: text("legal_name"),
  displayName: text("display_name").notNull(),
  timezone: text("timezone").notNull().default("America/Chicago"),
  contactEmail: text("contact_email").notNull(),
  onboardingStatus: text("onboarding_status").notNull().default("profile"),
  termsAcceptedAt: integer("terms_accepted_at", { mode: "timestamp" }),
  privacyAcceptedAt: integer("privacy_accepted_at", { mode: "timestamp" }),
  configuredBy: text("configured_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const billingEvents = sqliteTable("billing_events", {
  id: text("id").primaryKey(),
  academyId: text("academy_id"),
  providerEventId: text("provider_event_id").notNull(),
  eventType: text("event_type").notNull(),
  status: text("status").notNull(),
  payloadHash: text("payload_hash").notNull(),
  processedAt: integer("processed_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const backupRuns = sqliteTable("backup_runs", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  objectKey: text("object_key").notNull(),
  recordCount: integer("record_count").notNull(),
  byteSize: integer("byte_size").notNull(),
  checksum: text("checksum").notNull(),
  status: text("status").notNull(),
  verifiedAt: integer("verified_at", { mode: "timestamp" }),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const launchGateAssessments = sqliteTable("launch_gate_assessments", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  gateCode: text("gate_code").notNull(),
  status: text("status").notNull(),
  evidence: text("evidence"),
  assessedBy: text("assessed_by").notNull(),
  assessedAt: integer("assessed_at", { mode: "timestamp" }).notNull(),
});
export const requestCounters = sqliteTable("request_counters", {
  counterKey: text("counter_key").primaryKey(),
  windowStart: integer("window_start").notNull(),
  requestCount: integer("request_count").notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const academyProfiles = sqliteTable("academy_profiles", {
  academyId: text("academy_id").primaryKey(),
  legalName: text("legal_name").notNull(),
  displayName: text("display_name").notNull(),
  description: text("description").notNull(),
  addressLine1: text("address_line_1").notNull(),
  addressLine2: text("address_line_2"),
  city: text("city").notNull(),
  region: text("region").notNull(),
  postalCode: text("postal_code").notNull(),
  countryCode: text("country_code").notNull().default("US"),
  latitude: text("latitude"),
  longitude: text("longitude"),
  phone: text("phone"),
  website: text("website"),
  socialLinksJson: text("social_links_json").notNull().default("{}"),
  teamAffiliationsJson: text("team_affiliations_json").notNull().default("[]"),
  hoursJson: text("hours_json").notNull().default("{}"),
  claimStatus: text("claim_status").notNull().default("draft"),
  publicStatus: text("public_status").notNull().default("private"),
  updatedBy: text("updated_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const academyStaffProfiles = sqliteTable("academy_staff_profiles", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  displayName: text("display_name").notNull(),
  title: text("title").notNull(),
  email: text("email"),
  phone: text("phone"),
  bio: text("bio"),
  isPrimaryContact: integer("is_primary_contact", { mode: "boolean" }).notNull().default(false),
  publicContact: integer("public_contact", { mode: "boolean" }).notNull().default(false),
  status: text("status").notNull().default("active"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const userProfiles = sqliteTable("user_profiles", {
  userEmail: text("user_email").primaryKey(),
  displayName: text("display_name").notNull(),
  homeAcademyId: text("home_academy_id"),
  birthYear: integer("birth_year"),
  belt: text("belt"),
  locationText: text("location_text"),
  goals: text("goals"),
  concerns: text("concerns"),
  strengths: text("strengths"),
  weaknesses: text("weaknesses"),
  opportunities: text("opportunities"),
  socialLinksJson: text("social_links_json").notNull().default("{}"),
  teamAffiliationsJson: text("team_affiliations_json").notNull().default("[]"),
  visibility: text("visibility").notNull().default("private"),
  bookingEnabled: integer("booking_enabled", { mode: "boolean" }).notNull().default(false),
  avatarObjectKey: text("avatar_object_key"),
  avatarContentType: text("avatar_content_type"),
  avatarUpdatedAt: integer("avatar_updated_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const academyReviews = sqliteTable("academy_reviews", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  authorEmail: text("author_email").notNull(),
  rating: integer("rating").notNull(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  visitType: text("visit_type").notNull(),
  status: text("status").notNull().default("pending"),
  academyResponse: text("academy_response"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const academyConnections = sqliteTable("academy_connections", {
  id: text("id").primaryKey(),
  requesterAcademyId: text("requester_academy_id"),
  requesterEmail: text("requester_email").notNull(),
  targetAcademyId: text("target_academy_id").notNull(),
  connectionType: text("connection_type").notNull(),
  message: text("message"),
  status: text("status").notNull().default("requested"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const trainingBookings = sqliteTable("training_bookings", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  athleteEmail: text("athlete_email").notNull(),
  offeringType: text("offering_type").notNull(),
  startAt: integer("start_at", { mode: "timestamp" }).notNull(),
  durationMinutes: integer("duration_minutes").notNull(),
  partySize: integer("party_size").notNull().default(1),
  message: text("message"),
  status: text("status").notNull().default("requested"),
  priceCents: integer("price_cents"),
  currency: text("currency").notNull().default("usd"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const referralAttributions = sqliteTable("referral_attributions", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  referredUserEmail: text("referred_user_email").notNull(),
  code: text("code").notNull(),
  status: text("status").notNull().default("pending"),
  qualifiedAt: integer("qualified_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const revenueShareLedger = sqliteTable("revenue_share_ledger", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  attributionId: text("attribution_id"),
  providerInvoiceId: text("provider_invoice_id"),
  grossCents: integer("gross_cents").notNull(),
  eligibleNetCents: integer("eligible_net_cents").notNull(),
  shareBasisPoints: integer("share_basis_points").notNull().default(1000),
  shareCents: integer("share_cents").notNull(),
  entryType: text("entry_type").notNull(),
  status: text("status").notNull().default("pending"),
  availableAt: integer("available_at", { mode: "timestamp" }),
  paidAt: integer("paid_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const academyClaims = sqliteTable("academy_claims", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  claimantEmail: text("claimant_email").notNull(),
  claimantName: text("claimant_name").notNull(),
  claimantTitle: text("claimant_title").notNull(),
  evidenceType: text("evidence_type").notNull(),
  evidenceReference: text("evidence_reference").notNull(),
  status: text("status").notNull().default("submitted"),
  riskStatus: text("risk_status").notNull().default("review_required"),
  reviewedBy: text("reviewed_by"),
  reviewedAt: integer("reviewed_at", { mode: "timestamp" }),
  decisionNote: text("decision_note"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const membershipInvitations = sqliteTable("membership_invitations", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  email: text("email").notNull(),
  role: text("role").notNull(),
  status: text("status").notNull().default("pending"),
  tokenHash: text("token_hash").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  invitedBy: text("invited_by").notNull(),
  acceptedAt: integer("accepted_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const academyVerificationEvents = sqliteTable("academy_verification_events", {
  id: text("id").primaryKey(),
  academyId: text("academy_id").notNull(),
  claimId: text("claim_id"),
  eventType: text("event_type").notNull(),
  status: text("status").notNull(),
  evidenceHash: text("evidence_hash"),
  actorEmail: text("actor_email").notNull(),
  note: text("note"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const competitionPortfolios = sqliteTable("competition_portfolios", {
  id: text("id").primaryKey(),
  ownerEmail: text("owner_email").notNull(),
  athleteId: text("athlete_id"),
  displayName: text("display_name").notNull(),
  competitionName: text("competition_name").notNull(),
  birthYear: integer("birth_year"),
  academyName: text("academy_name"),
  currentRank: text("current_rank"),
  visibility: text("visibility").notNull().default("private"),
  verificationStatus: text("verification_status").notNull().default("self_reported"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const competitionResults = sqliteTable("competition_results", {
  id: text("id").primaryKey(),
  portfolioId: text("portfolio_id").notNull(),
  eventName: text("event_name").notNull(),
  eventDate: integer("event_date", { mode: "timestamp" }).notNull(),
  organizer: text("organizer").notNull(),
  locationText: text("location_text"),
  discipline: text("discipline").notNull(),
  ageDivision: text("age_division"),
  beltDivision: text("belt_division"),
  weightDivision: text("weight_division"),
  placement: integer("placement"),
  wins: integer("wins").notNull().default(0),
  losses: integer("losses").notNull().default(0),
  draws: integer("draws").notNull().default(0),
  submissionWins: integer("submission_wins").notNull().default(0),
  sourceUrl: text("source_url"),
  sourceRecordId: text("source_record_id"),
  verificationStatus: text("verification_status").notNull().default("self_reported"),
  verifiedBy: text("verified_by"),
  verifiedAt: integer("verified_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const externalCompetitionProfiles = sqliteTable("external_competition_profiles", {
  id: text("id").primaryKey(),
  portfolioId: text("portfolio_id").notNull(),
  provider: text("provider").notNull(),
  profileUrl: text("profile_url").notNull(),
  externalAthleteId: text("external_athlete_id"),
  claimedName: text("claimed_name"),
  matchStatus: text("match_status").notNull().default("unverified"),
  matchConfidence: integer("match_confidence"),
  lastCheckedAt: integer("last_checked_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const competitionEvidence = sqliteTable("competition_evidence", {
  id: text("id").primaryKey(),
  portfolioId: text("portfolio_id").notNull(),
  resultId: text("result_id"),
  objectKey: text("object_key").notNull(),
  fileName: text("file_name").notNull(),
  contentType: text("content_type").notNull(),
  byteSize: integer("byte_size").notNull(),
  sha256: text("sha256").notNull(),
  evidenceType: text("evidence_type").notNull(),
  sourceProvider: text("source_provider"),
  status: text("status").notNull().default("submitted"),
  uploadedBy: text("uploaded_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const recordVerificationEvents = sqliteTable("record_verification_events", {
  id: text("id").primaryKey(),
  portfolioId: text("portfolio_id").notNull(),
  resultId: text("result_id"),
  externalProfileId: text("external_profile_id"),
  eventType: text("event_type").notNull(),
  outcome: text("outcome").notNull(),
  confidence: integer("confidence"),
  reason: text("reason"),
  actorEmail: text("actor_email").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const athleteVerificationRequests = sqliteTable("athlete_verification_requests", {
  id: text("id").primaryKey(),
  athleteEmail: text("athlete_email").notNull(),
  athleteDisplayName: text("athlete_display_name").notNull(),
  academyName: text("academy_name").notNull(),
  verifierEmail: text("verifier_email").notNull(),
  claimedBirthYear: integer("claimed_birth_year").notNull(),
  claimedBelt: text("claimed_belt").notNull(),
  claimedMembershipStatus: text("claimed_membership_status").notNull().default("active"),
  status: text("status").notNull().default("pending_delivery"),
  tokenHash: text("token_hash").notNull(),
  tokenExpiresAt: integer("token_expires_at", { mode: "timestamp" }).notNull(),
  membershipConfirmed: integer("membership_confirmed", { mode: "boolean" }),
  ageConfirmed: integer("age_confirmed", { mode: "boolean" }),
  beltConfirmed: integer("belt_confirmed", { mode: "boolean" }),
  verifiedByName: text("verified_by_name"),
  verifiedByTitle: text("verified_by_title"),
  verifierNote: text("verifier_note"),
  respondedAt: integer("responded_at", { mode: "timestamp" }),
  verificationExpiresAt: integer("verification_expires_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const athleteVerificationEvents = sqliteTable("athlete_verification_events", {
  id: text("id").primaryKey(),
  requestId: text("request_id").notNull(),
  eventType: text("event_type").notNull(),
  outcome: text("outcome").notNull(),
  actorEmail: text("actor_email"),
  metadataJson: text("metadata_json"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
export const guardianConsents = sqliteTable("guardian_consents", {
  id: text("id").primaryKey(),
  minorEmail: text("minor_email").notNull(),
  guardianEmail: text("guardian_email").notNull(),
  guardianName: text("guardian_name"),
  relationship: text("relationship"),
  scopeJson: text("scope_json").notNull().default("[]"),
  status: text("status").notNull().default("pending_delivery"),
  tokenHash: text("token_hash").notNull(),
  tokenExpiresAt: integer("token_expires_at", { mode: "timestamp" }).notNull(),
  respondedAt: integer("responded_at", { mode: "timestamp" }),
  expiresAt: integer("expires_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const academyPayoutAccounts = sqliteTable("academy_payout_accounts", {
  academyId: text("academy_id").primaryKey(),
  stripeAccountId: text("stripe_account_id").notNull(),
  dashboardType: text("dashboard_type").notNull().default("express"),
  onboardingStatus: text("onboarding_status").notNull().default("pending"),
  transfersStatus: text("transfers_status").notNull().default("inactive"),
  payoutsStatus: text("payouts_status").notNull().default("inactive"),
  goodStanding: integer("good_standing", { mode: "boolean" }).notNull().default(true),
  detailsSubmitted: integer("details_submitted", { mode: "boolean" }).notNull().default(false),
  createdBy: text("created_by").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const revenueReceipts = sqliteTable("revenue_receipts", {
  id: text("id").primaryKey(),
  providerChargeId: text("provider_charge_id").notNull(),
  providerBalanceTransactionId: text("provider_balance_transaction_id"),
  currency: text("currency").notNull().default("usd"),
  grossCents: integer("gross_cents").notNull(),
  taxCents: integer("tax_cents").notNull().default(0),
  processingFeeCents: integer("processing_fee_cents").notNull().default(0),
  refundCents: integer("refund_cents").notNull().default(0),
  disputeCents: integer("dispute_cents").notNull().default(0),
  netCents: integer("net_cents").notNull(),
  status: text("status").notNull().default("reconciling"),
  periodKey: text("period_key").notNull(),
  cohortId: text("cohort_id"),
  occurredAt: integer("occurred_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const revenuePoolCohorts = sqliteTable("revenue_pool_cohorts", {
  id: text("id").primaryKey(),
  periodKey: text("period_key").notNull(),
  currency: text("currency").notNull().default("usd"),
  netRevenueCents: integer("net_revenue_cents").notNull(),
  operationsCents: integer("operations_cents").notNull(),
  founderCents: integer("founder_cents").notNull(),
  academyPoolCents: integer("academy_pool_cents").notNull(),
  eligibleAcademyCount: integer("eligible_academy_count").notNull(),
  remainderCents: integer("remainder_cents").notNull().default(0),
  reserveDays: integer("reserve_days").notNull().default(60),
  availableAt: integer("available_at", { mode: "timestamp" }).notNull(),
  status: text("status").notNull().default("reserved"),
  closedBy: text("closed_by").notNull(),
  closedAt: integer("closed_at", { mode: "timestamp" }).notNull(),
  releasedAt: integer("released_at", { mode: "timestamp" }),
});
export const academyPoolAllocations = sqliteTable("academy_pool_allocations", {
  id: text("id").primaryKey(),
  cohortId: text("cohort_id").notNull(),
  academyId: text("academy_id").notNull(),
  stripeAccountId: text("stripe_account_id").notNull(),
  amountCents: integer("amount_cents").notNull(),
  currency: text("currency").notNull().default("usd"),
  status: text("status").notNull().default("reserved"),
  providerTransferId: text("provider_transfer_id"),
  attempts: integer("attempts").notNull().default(0),
  failureCode: text("failure_code"),
  paidAt: integer("paid_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const founderDistributions = sqliteTable("founder_distributions", {
  id: text("id").primaryKey(),
  cohortId: text("cohort_id").notNull(),
  amountCents: integer("amount_cents").notNull(),
  currency: text("currency").notNull().default("usd"),
  status: text("status").notNull().default("payable"),
  authorizedBy: text("authorized_by"),
  paidAt: integer("paid_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const accountDeletionRequests = sqliteTable("account_deletion_requests", {
  id: text("id").primaryKey(),
  userEmail: text("user_email").notNull(),
  status: text("status").notNull().default("scheduled"),
  reason: text("reason"),
  scheduledFor: integer("scheduled_for", { mode: "timestamp" }).notNull(),
  legalHold: integer("legal_hold", { mode: "boolean" }).notNull().default(false),
  completedAt: integer("completed_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const contentReports = sqliteTable("content_reports", {
  id: text("id").primaryKey(),
  reporterEmail: text("reporter_email").notNull(),
  subjectType: text("subject_type").notNull(),
  subjectId: text("subject_id").notNull(),
  reason: text("reason").notNull(),
  details: text("details"),
  status: text("status").notNull().default("received"),
  priority: text("priority").notNull().default("standard"),
  reviewedBy: text("reviewed_by"),
  reviewedAt: integer("reviewed_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const userBlocks = sqliteTable("user_blocks", {
  id: text("id").primaryKey(),
  blockerEmail: text("blocker_email").notNull(),
  blockedEmail: text("blocked_email").notNull(),
  status: text("status").notNull().default("active"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
export const moderationActions = sqliteTable("moderation_actions", {
  id: text("id").primaryKey(),
  reportId: text("report_id"),
  actorEmail: text("actor_email").notNull(),
  action: text("action").notNull(),
  subjectType: text("subject_type").notNull(),
  subjectId: text("subject_id").notNull(),
  rationale: text("rationale").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});
