// Generates app/lib/version.ts from the VERSION file so the running application
// reports the same version the release train approved. Run by `prebuild`;
// release:preflight fails the build if the generated file has drifted.
import { readFileSync, writeFileSync } from "node:fs";

const version = readFileSync("VERSION", "utf8").trim();
const banner = "// GENERATED BY scripts/sync-version.mjs FROM VERSION -- DO NOT EDIT BY HAND.\n";
const body = `${banner}export const APP_VERSION = ${JSON.stringify(version)};\n`;

let current = "";
try {
  current = readFileSync("app/lib/version.ts", "utf8");
} catch {}

if (current !== body) {
  writeFileSync("app/lib/version.ts", body);
  console.log(`app/lib/version.ts -> ${version}`);
} else {
  console.log(`app/lib/version.ts already at ${version}`);
}
